package com.davidoladeji.flexisaf.bootstrap;

import com.davidoladeji.flexisaf.model.Department;
import com.davidoladeji.flexisaf.model.Student;
import com.davidoladeji.flexisaf.repository.DepartmentRepository;
import com.davidoladeji.flexisaf.repository.StudentRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

@Component
public class DepartmentLoader implements CommandLineRunner {

    public final DepartmentRepository departmentRepository;


    public DepartmentLoader(DepartmentRepository departmentRepository) {
        this.departmentRepository = departmentRepository;
    }

    @Override
    public void run(String... args) throws Exception {
        createDepartments();
    }


    private void createDepartments() {
        if (departmentRepository.count() == 0) {
            departmentRepository.save(
                    Department.builder()
                            .name("Computer Science")
                            .build()
            );
            departmentRepository.save(
                    Department.builder()
                            .name("Electrical Engineering")
                            .build()
            );
            departmentRepository.save(
                    Department.builder()
                            .name("Biochemistry")
                            .build()
            );
            departmentRepository.save(
                    Department.builder()
                            .name("Microbiology")
                            .build()
            );
            System.out.println("Departments default data autogenerated in database");
        }
    }
}
