package com.davidoladeji.ozeguru.controller;

import com.davidoladeji.ozeguru.model.Patient;
import com.davidoladeji.ozeguru.model.Staff;
import com.davidoladeji.ozeguru.repository.PatientRepository;
import com.davidoladeji.ozeguru.service.PatientService;
import com.davidoladeji.ozeguru.service.StaffService;
import com.davidoladeji.ozeguru.service.implementation.StaffServiceImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.supercsv.io.CsvBeanWriter;
import org.supercsv.io.ICsvBeanWriter;
import org.supercsv.prefs.CsvPreference;

import javax.servlet.http.HttpServletResponse;
import javax.validation.Valid;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;


@RestController
@RequestMapping("/api/v1/public/")
public class PublicController {


    @Autowired
    private StaffService staffService;


    /**
     * Adds a new staff and assigns autogenerated UUID // Requirement 1
     */
    @PostMapping("staff/add")
    public ResponseEntity<Object> addStaff(@Valid @RequestBody Staff staff) {
        Staff createdStaff = staffService.addStaff(staff);
        return new ResponseEntity<>(createdStaff, HttpStatus.CREATED);
    }


}