package com.davidoladeji.ozeguru.bootstrap;

import com.davidoladeji.ozeguru.model.Patient;
import com.davidoladeji.ozeguru.model.Staff;
import com.davidoladeji.ozeguru.repository.PatientRepository;
import com.davidoladeji.ozeguru.repository.StaffRepository;
import com.github.javafaker.Faker;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.security.SecureRandom;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.UUID;

@Component
public class PatientLoader implements CommandLineRunner {

    public final PatientRepository patientRepository;


    public PatientLoader(PatientRepository patientRepository) {
        this.patientRepository = patientRepository;
    }

    @Override
    public void run(String... args) {
        createPatient();
    }
    private void createPatient() {

        Faker faker = new Faker(new Locale("en-US"));
        int max = 200;

        if (patientRepository.count() == 0) {
            patientRepository.save(
                    Patient.builder()
                            .name("Joe Oladeji")
                            .age(27)
                            .last_visit_date(faker.date().birthday(1,3))
                            .build()
            );
            for(int i = 0; i < max; i++) {
                patientRepository.save(
                        Patient.builder()
                                .name(faker.name().fullName())
                                .age(faker.number().numberBetween(1,60))
                                .last_visit_date(faker.date().birthday(1,3))
                                .build()
                );
            }



            System.out.println("Patient default data autogenerated in database");
        }


    }
}
