package com.davidoladeji.ozeguru.bootstrap;

import com.davidoladeji.ozeguru.model.Staff;
import com.davidoladeji.ozeguru.repository.StaffRepository;
import com.github.javafaker.Faker;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.security.SecureRandom;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.UUID;

@Component
public class StaffLoader implements CommandLineRunner {

    private static final SecureRandom random = new SecureRandom();

    final String uuid = UUID.randomUUID().toString().replace("-", "");
    public final StaffRepository staffRepository;


    public StaffLoader(StaffRepository studentRepository) {
        this.staffRepository = studentRepository;
    }

    @Override
    public void run(String... args) throws Exception {
        createStaff();
    }
    private void createStaff() throws ParseException {
        Faker faker = new Faker(new Locale("en-US"));
        int max = 100;

        if (staffRepository.count() == 0) {
            staffRepository.save(
                    Staff.builder()
                            .name("David Oladeji")
                            .username("daveola")
                            .password("mydream")
                            .build()
            );
            for(int i = 0; i < max; i++) {
                staffRepository.save(
                        Staff.builder()
                                .name(faker.name().fullName())
                                .username(faker.name().username())
                                .password(faker.name().name())
                                .build()
                );
            }



            System.out.println("Staff default data autogenerated in database");
        }


    }
}
